version: '3'

services:
  caddy:
    image: caddy:latest
    container_name: caddy_test
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./dist:/srv/dist
      - ./caddydata:/data
    ports:
      - "80:80"
      - "443:443"
  php_file_service:
    restart: unless-stopped
    image: php:8.2-alpine
    volumes:
      - ./public/:/var/www/html/
      - ./data/:/var/www/html/root
    ports:
      - "8081:80"
    command: ["php", "-S", "0.0.0.0:80", "-t", "/var/www/html/", "/var/www/html/server.php"]