version: '3'

services:
  caddy:
    image: caddy:latest
    container_name: caddy_test
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./dist:/srv
      - ./caddydata:/data
    ports:
      - "80:80"
      - "443:443"
